package:
  name: isj_presentation

source:
  git_url: https://github.com/KrazyIII/ISJ_presentation.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jupyter_contrib_nbextensions

test:
  imports:
    - code_url
    - compare_code

about:
  home: https://github.com/KrazyIII/ISJ_presentation